openapi: 3.0.4
info:
  title: Music Note Generator
  description: >-
    Music Note Generator creates high-quality WAV audio files of musical notes
    with precise frequency generation and customizable duration.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/musicnotegenerator:
    get:
      summary: Generate Musical Note
      description: Generate audio file for musical note
      operationId: musicnotegenerator
      parameters:
        - name: note
          in: query
          schema:
            type: string
          required: true
          description: 'Musical note (A-G with optional # or b)'
          example: C
        - name: octave
          in: query
          schema:
            type: integer
          required: false
          description: Octave number
          example: 4
        - name: duration
          in: query
          schema:
            type: number
          required: false
          description: Duration in seconds
          example: 1
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  note: C
                  octave: 4
                  frequency: 261.63
                  duration: 1
                  audio:
                    audioFile: 72510463-6388-4588-8e08-5714f20f9c67.wav
                    format: .wav
                    downloadURL: >-
                      https://storage.googleapis.com/apiverve/APIData/musicnotegenerator/72510463-6388-4588-8e08-5714f20f9c67.wav?GoogleAccessId=635500398038-compute%40developer.gserviceaccount.com&Expires=1765925810&Signature=djWUb%2B8QmrAZLTEDiPAIB%2Bx7w7OYyJiClHTcPtkIvvtlKT01z%2FxJMMjUMvUHTx0aRpF94Oq5jdFKBqw2NPKOaEQPNIeF%2BukRt3cS5chrLI3ynvnLobkz4%2FrTGXW8r2BE42oWGMC1xjTJpdU5IMQjhEmWDMRPWzJo5sy6ZQAll5US9DtSVl7Tc2wyHCZRlxcTxlOLPCWv9SZ6Mn8i4kSXITWwp2FaR%2BEdJOi6bpRYkBBmWvnLlAiNFTm44v5QKm7dwXpAAyoidJ4%2Bo%2B2OErXHJ%2BTDMiLwFHZAc4Bt4slYTX5henGIt752fCoj2%2FOaLWSXp%2BnJNFkvKdKxVpDH40y%2FqA%3D%3D
                    duration: 1.00s
                    sampleRate: 44100Hz
                    bitDepth: 16-bit
                    expires: 1765925810991
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
