openapi: 3.0.4
info:
  title: Music Note Generator
  description: Music Note Generator creates high-quality WAV audio files of musical notes with precise frequency generation and customizable duration.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/musicnotegenerator:
    get:
      summary: Generate Musical Note
      description: Music Note Generator creates high-quality WAV audio files of musical notes with precise frequency generation and customizable duration.
      operationId: musicnotegenerator
      parameters:
      - name: note
        in: query
        schema:
          type: string
        required: true
        description: 'Musical note (A-G with optional # or b)'
        example: C
      - name: octave
        default: '4'
        in: query
        schema:
          type: number
        required: false
        description: Octave number (0-8)
        example: '4'
      - name: duration
        default: '1.0'
        in: query
        schema:
          type: number
        required: false
        description: Duration in seconds (0.1-10)
        example: '1.0'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  note: C
                  octave: 4
                  frequency: 261.63
                  duration: 1
                  audio:
                    audioFile: d37525eb-113e-4ee5-9d66-36c11a8cc6bc.wav
                    format: .wav
                    downloadURL: https://storage.googleapis.com/apiverve.appspot.com/musicnotegenerator/d37525eb-113e-4ee5-9d66-36c11a8cc6bc.wav?GoogleAccessId=635500398038-compute%40developer.gserviceaccount.com&Expires=1763589297&Signature=OOhnvCAiyt93A8jiQIcpgWIQEa2TDdGJYY4yF57AeGnNhH6baDldU8RmhBdZ8%2B8%2Ff1K6uA5Q7wKA0MNijeW%2BdjeWLhuirqhokHAWUjemKgOMNhheP%2BA7E0cDEiXxgWv1x9gBdpd97EgoO1u3NZGJfOyhoCOj%2FhZO1aVFMWd9ciW2EJxgGjofCCvPlwlyt6cUKXP61qyh1ULk0Pq1fpLaNXLSTYPof3LWinTVaRO6ffDA0VgHlvndRQRysr%2BKCdt7lYv6z156hAUPBq7s3cXoUFpt1zTxpjxOY2BQQvkFleJBxb9yhDXLjLMX7pbkAVnkEaXAE3OdpeOhNCxtDgAamQ%3D%3D
                    duration: 1.00s
                    sampleRate: 44100Hz
                    bitDepth: 16-bit
                    expires: 1763589297902
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
